org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
#if some error occurs, please remove this line or set it to false and try again
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
#if some error occurs, please remove this line or set it to false and try again
kotlin.incremental=false
kotlin.jvm.target.validation.mode=IGNORE